### ISSUE TITLE
Map Service

### ISSUE THREAD

**Issue by burningrain** [burningrain/planetBot#1]
Необходимо сделать возможность загрузки карт для бота из популярного формата для описания графов - https://ru.wikipedia.org/wiki/DOT_(%D1%8F%D0%B7%D1%8B%D0%BA) http://www.graphviz.org/Documentation/dotguide.pdf
Возможно, хорошие парсеры и билдеры ужу существуют (https://github.com/shevek/graphviz4j)
http://zvtm.sourceforge.net/zgrviewer/doc/ajapad/dotParser.html
https://github.com/nidi3/graphviz-java
https://mvnrepository.com/open-source/graphviz-libraries
надо поискать
https://wiki.eclipse.org/GEF/GEF4/DOT/User_Guide
http://git.eclipse.org/c/

**Comment by mrzo0m** [comment]
Смотрим в сторону http://ftp.acc.umu.se/mirror/eclipse.org/tools/gef/gef4/updates/releases/4.0.0_gef4-master_3401/features/  . Есть готовые бандлы с парсером .gv

**Comment by mrzo0m** [comment]
Продолжение таски: Необходимо обговорить использование map-service в других бандлах, и допилить сервисный метод бандла.

**Comment by burningrain** [comment]
насчет использования идея такова:
в ui-ный бандл (сейчас это main-app) подрубается в maven и bnd (да, дублирование) библиотека map-api. Далее надо допилить ui, чтобы он давал возможность выбора конкретной мапы (просто отображение списка названий карт через сервис, и выбор конкретной карты при клике на карту в списке и, н-р, нажатие на кнопку выбрать. Короче, как в старкрафте). 
Сам map-service просто кладется в osgi-контейнер и запускается вместе с контейнером. В нашем случае его можно положить в:
- osgi\bundles\app (думаю, пока можно закинуть сюда)
- osgi\bundles\ (старт вместе с контейнером)
- plugins  (а сюда, может, потом перенесем)
- strategies
- game-api
- cfg (fileinstall может видеть изменение в файле конфигурации и на лету переконфигурировать managed service)
(пояснение: все наши бандлы делятся на те, которые стартуют сразу с контейнером и те, которые инсталлируются и запускаются через felixinstall, порядок указан в файле config-fileinstall.properties)

 Соответствующий osgi-сервис (реализация интерфейса из map-api) сам занесет себя в реестр сервисов и заинжектится по месту интерфейса, указанного в map-api (см. osgi whiteboard pattern)

**Comment by burningrain** [comment]
Добавил сборку + в ui при клике на старт возможность выбора мапы.

Короче, че осталось:
Идея такова, что стираем bnd-природу из jar-иков, если надо, и пакуем jar-ники в бандл, указав в класспасе бандла искать в джарниках. 

Для этого необходимо:
1) взять и подрубить в мавен-депенденси xtext или как там ее
2) добавить в bnd в Bundle-Classpath название джарника, как в случае с либами эклипса.
3) собирать, запускать и надеяться, что взлетит. Если нет, искать где следующий пакет.
4) Искать следующий пакет….
5) …
6) PROFIT

ну, и пофиксать если где-то валит. С bndrun не заморачивался.

**Comment by burningrain** [comment]
И все-аки стоит рассмотреть связку:
+ graphml в качестве формата
+ yEd в качестве редактора

возможно, подрубим как еще одну имплментацию map-api

**Comment by mrzo0m** [comment]
http://mdaines.github.io/viz.js/
Web based .gv vizualizer, can use for maps tuning

**Comment by mrzo0m** [comment]
- Необходимо проработать механизм валидации карты

- Продумать механизм выбрасывания исключений с информацией

**Comment by burningrain** [comment]
+ Добавить параметр в .gv "максимальное число игроков"
+ на стороне ui после выбора карты добавить окно с выбором стратегий

**Comment by burningrain** [comment]
рабочий парсер теперь у нас есть) Предлагаю вмержить в основную ветку сделанные изменения, а остальные перечисленные моменты тогда оформить в виде отдельных задач, и эту таску закрыть. 
А то ветка уже распухать начала)

**Comment by mrzo0m** [comment]
Мастер ветка получила парсер. Ура закрываем ишю. Пабам
