### ISSUE TITLE
UI crash when load map

### ISSUE THREAD

**Issue by mrzo0m** [burningrain/planetBot#3]
```
private class UglyHuckRenderer extends BasicRenderer<Planet, String>{
   super .....
}

```
`Point2D p = (Point2D)layout.transform(v);`
после этого 
p=null
и падает 
`float x = (float)p.getX();`

```
	private final Set<Planet> planets;
	private final Set<Planet> startPoints;

```
Связывать не по обжектам а по ид планет в Сете

**Comment by burningrain** [comment]
Корень проблемы был в том, что не заполнялись соседи, и некорректно копировался объект Galaxy в GalaxyEngine. Залил фикс, надо убедиться, что все норм.

**Comment by mrzo0m** [comment]
Все норм
