### ISSUE TITLE
map service validation

### ISSUE THREAD

**Issue by burningrain** [burningrain/planetBot#5]
В парсер необходимо добавить валидацию. Предлагаю сделать в парсере простую валидацию обязательных и необязательных параметров. В случае отсутствия обязательного параметра выкидывать исключение (н-р, MapValidationException, который расположить в map-api).
То есть парсер будет валидировать исключительно корректность формата. 
Более сложная валидация, включающая в себя логику и зависимость одних параметров от других (н-р, что на карте "большие базы" должна быть только одна малая планета) будет размещаться в game-core. Проверка корректности галактики будет происходить при попытке создания игры. И в случае некорректности выкидываться исключение.
Такая "размазанность" валидации сделает парсер более тупым, а значит:
1)  упростит переход на новый формат и написание нового парсера (не придется дублировать сложные логические проверки в новом парсере)
2) двигло остается защищенным, и не начнет обработку некорректной галактики.И это независимо от того, откуда галактика получена (ну а вдруг не из парсера?! Ну, мало ли...). 
3) в случае нескольких движков у каждого из них может свое представление о корректности галактики (н-р, один считает нормальным планеты без связей, а другой нет и т.п.), поэтому эта логика валидации в теории может различаться.
4) имхо, вполне логично валидировать данные тому, кто их получает. Галактику получает движок, а не парсер. Парсер получает .gv файл и отдает галактику движку.  Иллюстрация к моей мысли - это работа технического переводчика. Он может перевести технический текст с английского на русский, но он может не понимать сам предмет. Насколько плохо он перевел, понимает специалист в технической области, который, однако, не понимает исходный английский язык. Задача переводчика в данном случае сводится к тому, чтобы перевести текст так, чтобы спец поменьше матерился, читая данный перевод. Но это не значит, что переводчик должен знать тонкости технического предмета.

Поскольку понимания логических условий прямо сейчас нет, то надо сделать просто проверки обязательных/необязательных параметров, относящихся к формату. Если что, прямо тут и продолжим обсуждение.

**Comment by mrzo0m** [comment]
Для не семантической валидации предлагаю взять либу https://github.com/daveclayton/json-schema-validator

**Comment by burningrain** [comment]
да не вопрос) Надо подумать над тем, какие параметры являются обязательными, а какие опциональными на текущем этапе.

**Comment by mrzo0m** [comment]
В рамках таски необходимо включить либу схемы в состав бандла, разобраться с импорт/экспорт пакета OSGi

**Comment by mrzo0m** [comment]
Схемы вшиты в бандл сервиса карт. Добавлены схемы для планет и галактики. На UI отображается инфа о том почему карта не правильная.
